import QtQuick
import QtQuick.Window
import org.freedesktop.gstreamer.Qt6GLVideoItem 1.0 // Dynamic generated by GStreamer Qt6 QML plugin

Window {
    id: window
    width: 1280
    height: 720
    visible: true
    title: "DJI Robomaster Client HUD"
    color: "black"

    // 假设顶部队伍基础最大血量为 2000 (你可以根据实际 viewModel 里的最大值调整)
    property int maxTeamHp: 5000

    // 主题色设定
    property color colorCyan: "#00e5ff"
    property color colorRed: "#ff2a40"
    property color colorBlue: "#2a80ff"
    property color colorWarning: "#ffb700"
    property color colorHudBg: "#40000000"

    // Background Container for Video and UI
    Item {
        anchors.fill: parent

        GstGLQt6VideoItem {
            id: video
            objectName: "videoItem"
            anchors.centerIn: parent
            width: parent.width
            height: parent.height
        }

        // --- HUD OVERLAY 遮罩层 (增加屏幕边缘暗角，突出中间视频) ---
        Rectangle {
            anchors.fill: parent
            gradient: Gradient {
                GradientStop {
                    position: 0.0
                    color: "#60000000"
                }
                GradientStop {
                    position: 0.1
                    color: "transparent"
                }
                GradientStop {
                    position: 0.9
                    color: "transparent"
                }
                GradientStop {
                    position: 1.0
                    color: "#80000000"
                }
            }
        }

        // ==========================================
        // 2. Top Bar UI Layer (战局信息)
        // ==========================================
        Item {
            id: topHud
            width: parent.width
            height: 80
            anchors.top: parent.top

            // 顶部装饰线
            Rectangle {
                width: parent.width
                height: 2
                color: window.colorCyan
                opacity: 0.3
                anchors.top: parent.top
            }

            // --- 红方 (Red Team) ---
            Item {
                width: 300
                height: 40
                anchors.left: parent.left
                anchors.leftMargin: 80
                anchors.verticalCenter: parent.verticalCenter

                Text {
                    id: redTeamLabel
                    text: "RED TEAM"
                    color: window.colorRed
                    font.pixelSize: 12
                    font.family: "Fira Code"
                    font.bold: true
                    anchors.bottom: redHpContainer.top
                    anchors.bottomMargin: 4
                }

                // 动态血条外框
                Rectangle {
                    id: redHpContainer
                    width: parent.width
                    height: 12
                    color: window.colorHudBg
                    border.color: "#80ff2a40"
                    anchors.bottom: parent.bottom

                    // 动态血条填充
                    Rectangle {
                        height: parent.height
                        // 动态计算宽度，防止除 0 或越界
                        width: Math.max(0, Math.min((viewModel.redHp / maxTeamHp), 1.0)) * parent.width
                        color: window.colorRed
                        anchors.right: parent.right // 红队血条从右向左扣

                        // 动画效果：数值变化时平滑过渡
                        Behavior on width {
                            NumberAnimation {
                                duration: 300
                                easing.type: Easing.OutQuad
                            }
                        }
                    }
                }

                Text {
                    text: viewModel.redHp
                    color: "white"
                    font.pixelSize: 20
                    font.family: "Fira Code"
                    font.bold: true
                    anchors.bottom: redHpContainer.top
                    anchors.right: redHpContainer.right
                }
            }

            // --- 中间计时器 (Timer) ---
            Item {
                width: 160
                height: 60
                anchors.centerIn: parent

                // 装饰性括号 [ ]
                Text {
                    text: "["
                    color: window.colorCyan
                    font.pixelSize: 40
                    anchors.left: parent.left
                    anchors.verticalCenter: parent.verticalCenter
                    opacity: 0.5
                }
                Text {
                    text: "]"
                    color: window.colorCyan
                    font.pixelSize: 40
                    anchors.right: parent.right
                    anchors.verticalCenter: parent.verticalCenter
                    opacity: 0.5
                }

                Text {
                    text: viewModel.battleTimeSec ? viewModel.battleTimeSec.toString() : "000"
                    color: window.colorCyan
                    font.pixelSize: 36
                    font.family: "Fira Code"
                    anchors.centerIn: parent
                    font.bold: true
                    style: Text.Outline
                    styleColor: window.colorCyan // 发光效果替代品
                }
                Text {
                    text: "T-MINUS"
                    color: window.colorCyan
                    font.pixelSize: 10
                    font.family: "Fira Code"
                    anchors.top: parent.top
                    anchors.horizontalCenter: parent.horizontalCenter
                    opacity: 0.7
                }
            }

            // --- 蓝方 (Blue Team) ---
            Item {
                width: 300
                height: 40
                anchors.right: parent.right
                anchors.rightMargin: 80
                anchors.verticalCenter: parent.verticalCenter

                Text {
                    id: blueTeamLabel
                    text: "BLUE TEAM"
                    color: window.colorBlue
                    font.pixelSize: 12
                    font.family: "Fira Code"
                    font.bold: true
                    anchors.bottom: blueHpContainer.top
                    anchors.bottomMargin: 4
                    anchors.right: parent.right
                }

                // 动态血条外框
                Rectangle {
                    id: blueHpContainer
                    width: parent.width
                    height: 12
                    color: window.colorHudBg
                    border.color: "#802a80ff"
                    anchors.bottom: parent.bottom

                    // 动态血条填充
                    Rectangle {
                        height: parent.height
                        width: Math.max(0, Math.min((viewModel.blueHp / maxTeamHp), 1.0)) * parent.width
                        color: window.colorBlue
                        anchors.left: parent.left // 蓝队血条从左向右扣
                        Behavior on width {
                            NumberAnimation {
                                duration: 300
                                easing.type: Easing.OutQuad
                            }
                        }
                    }
                }

                Text {
                    text: viewModel.blueHp
                    color: "white"
                    font.pixelSize: 20
                    font.family: "Fira Code"
                    font.bold: true
                    anchors.bottom: blueHpContainer.top
                    anchors.left: blueHpContainer.left
                }
            }
        }

        // ==========================================
        // 3. Center Crosshair (机甲光学准星)
        // ==========================================
        Item {
            anchors.centerIn: parent
            width: 300
            height: 300

            // 中心瞄准点
            Rectangle {
                width: 4
                height: 4
                radius: 2
                color: window.colorCyan
                anchors.centerIn: parent
                // 中心点轻微呼吸动画
                SequentialAnimation on opacity {
                    loops: Animation.Infinite
                    NumberAnimation {
                        from: 1.0
                        to: 0.3
                        duration: 800
                    }
                    NumberAnimation {
                        from: 0.3
                        to: 1.0
                        duration: 800
                    }
                }
            }

            // 左侧准星括号
            Item {
                width: 20
                height: 80
                anchors.verticalCenter: parent.verticalCenter
                anchors.right: parent.horizontalCenter
                anchors.rightMargin: 40
                Rectangle {
                    width: 2
                    height: parent.height
                    color: window.colorCyan
                    anchors.left: parent.left
                    opacity: 0.8
                }
                Rectangle {
                    width: 12
                    height: 2
                    color: window.colorCyan
                    anchors.left: parent.left
                    anchors.top: parent.top
                    opacity: 0.8
                }
                Rectangle {
                    width: 12
                    height: 2
                    color: window.colorCyan
                    anchors.left: parent.left
                    anchors.bottom: parent.bottom
                    opacity: 0.8
                }
            }

            // 右侧准星括号
            Item {
                width: 20
                height: 80
                anchors.verticalCenter: parent.verticalCenter
                anchors.left: parent.horizontalCenter
                anchors.leftMargin: 40
                Rectangle {
                    width: 2
                    height: parent.height
                    color: window.colorCyan
                    anchors.right: parent.right
                    opacity: 0.8
                }
                Rectangle {
                    width: 12
                    height: 2
                    color: window.colorCyan
                    anchors.right: parent.right
                    anchors.top: parent.top
                    opacity: 0.8
                }
                Rectangle {
                    width: 12
                    height: 2
                    color: window.colorCyan
                    anchors.right: parent.right
                    anchors.bottom: parent.bottom
                    opacity: 0.8
                }
            }

            // 俯仰角虚线指示器 (Pitch Lines)
            Row {
                anchors.centerIn: parent
                spacing: 60
                Rectangle {
                    width: 30
                    height: 1
                    color: window.colorCyan
                    opacity: 0.4
                }
                Rectangle {
                    width: 30
                    height: 1
                    color: window.colorCyan
                    opacity: 0.4
                }
            }

            // 下方锁定提示文字
            Text {
                text: "AUTO-AIM OFFLINE"
                color: window.colorCyan
                font.pixelSize: 10
                font.family: "Fira Code"
                anchors.horizontalCenter: parent.horizontalCenter
                anchors.top: parent.verticalCenter
                anchors.topMargin: 50
                opacity: 0.6
            }
        }

        // ==========================================
        // 4. Bottom Left Status Panel (自身机甲状态)
        // ==========================================
        Item {
            id: statusPanel
            width: 350
            height: 140
            anchors.left: parent.left
            anchors.bottom: parent.bottom
            anchors.leftMargin: 40
            anchors.bottomMargin: 40

            // 装饰性 HUD 底线
            Rectangle {
                width: parent.width
                height: 1
                color: window.colorCyan
                opacity: 0.5
                anchors.bottom: parent.bottom
            }

            Column {
                anchors.fill: parent
                spacing: 12

                // --- 血量模块 (ARMOR) ---
                Item {
                    width: parent.width
                    height: 40

                    Text {
                        text: "SYS.ARMOR"
                        color: (viewModel.currentHp / viewModel.maxHp) < 0.3 ? window.colorRed : window.colorCyan
                        font.pixelSize: 14
                        font.family: "Fira Code"
                        font.bold: true
                        anchors.left: parent.left
                        anchors.bottom: selfHpBar.top
                        anchors.bottomMargin: 6
                    }

                    Text {
                        text: viewModel.currentHp + " / " + viewModel.maxHp
                        color: "white"
                        font.pixelSize: 16
                        font.family: "Fira Code"
                        anchors.right: parent.right
                        anchors.bottom: selfHpBar.top
                        anchors.bottomMargin: 6
                    }

                    // 自身血条
                    Rectangle {
                        id: selfHpBar
                        width: parent.width
                        height: 16
                        color: window.colorHudBg
                        border.color: (viewModel.currentHp / viewModel.maxHp) < 0.3 ? "#80ff2a40" : "#8000e5ff"
                        anchors.bottom: parent.bottom

                        // 分段网格遮罩 (制造科幻科幻机甲风血条的分段感)
                        Row {
                            anchors.fill: parent
                            spacing: 2
                            Repeater {
                                model: 30
                                Rectangle {
                                    width: (parent.width - 29 * 2) / 30
                                    height: parent.height
                                    color: "transparent"
                                    border.color: "#33000000"
                                    border.width: 1
                                    z: 2
                                }
                            }
                        }

                        // 实际血量填充
                        Rectangle {
                            height: parent.height
                            width: viewModel.maxHp > 0 ? Math.max(0, Math.min((viewModel.currentHp / viewModel.maxHp), 1.0)) * parent.width : 0
                            color: (viewModel.currentHp / viewModel.maxHp) < 0.3 ? window.colorRed : window.colorCyan

                            // 颜色和宽度双重动画
                            Behavior on width {
                                NumberAnimation {
                                    duration: 200
                                    easing.type: Easing.OutQuad
                                }
                            }
                            Behavior on color {
                                ColorAnimation {
                                    duration: 300
                                }
                            }
                        }
                    }
                }

                // --- 弹药与电量模块 (WEAPON & POWER) ---
                Row {
                    width: parent.width
                    spacing: 40

                    // 弹药 (AMMO) - 大号字体强调
                    Column {
                        spacing: 2
                        Text {
                            text: "MAG.AMMO"
                            color: viewModel.currentAmmo <= 20 ? window.colorWarning : window.colorCyan
                            font.pixelSize: 14
                            font.family: "Fira Code"
                            font.bold: true
                        }
                        Text {
                            text: viewModel.currentAmmo
                            color: viewModel.currentAmmo <= 20 ? window.colorWarning : "white"
                            font.pixelSize: 42
                            font.family: "Fira Code"
                            font.bold: true
                        }
                    }

                    // 假定预留：枪管热量/辅助能量 (HEAT / PWR)
                    Column {
                        spacing: 2
                        Text {
                            text: "HEAT"
                            color: colorCyan
                            font.pixelSize: 14
                            font.family: "Fira Code"
                        }
                        Rectangle {
                            width: 100
                            height: 10
                            color: colorHudBg
                            border.color: "#8000e5ff"
                            Rectangle {
                                width: 30
                                height: parent.height
                                color: colorCyan
                                opacity: 0.6
                            } // 静态占位
                        }
                    }
                }
            }
        }

        // ==========================================
        // 5. Bottom Right Minimap (雷达小地图)
        // ==========================================
        Item {
            id: minimap
            width: 220
            height: 220
            anchors.right: parent.right
            anchors.bottom: parent.bottom
            anchors.rightMargin: 40
            anchors.bottomMargin: 40

            // 外部雷达圈
            Rectangle {
                anchors.fill: parent
                color: window.colorHudBg
                border.color: window.colorCyan
                border.width: 1
                radius: width / 2
                opacity: 0.8

                // 内圈线
                Rectangle {
                    anchors.centerIn: parent
                    width: parent.width * 0.6
                    height: parent.height * 0.6
                    color: "transparent"
                    border.color: window.colorCyan
                    border.width: 1
                    radius: width / 2
                    opacity: 0.3
                }

                // 十字基准线
                Rectangle {
                    width: parent.width
                    height: 1
                    color: window.colorCyan
                    anchors.centerIn: parent
                    opacity: 0.3
                }
                Rectangle {
                    width: 1
                    height: parent.height
                    color: window.colorCyan
                    anchors.centerIn: parent
                    opacity: 0.3
                }

                // 模拟扫描扇形（用一段文字代表）
                Text {
                    text: "RADAR\nONLINE"
                    color: window.colorCyan
                    font.pixelSize: 10
                    font.family: "Fira Code"
                    anchors.centerIn: parent
                    horizontalAlignment: Text.AlignHCenter
                    opacity: 0.5
                }
            }

            // 雷达四角科技框
            Rectangle {
                width: 15
                height: 2
                color: window.colorCyan
                anchors.top: parent.top
                anchors.left: parent.left
            }
            Rectangle {
                width: 2
                height: 15
                color: window.colorCyan
                anchors.top: parent.top
                anchors.left: parent.left
            }

            Rectangle {
                width: 15
                height: 2
                color: window.colorCyan
                anchors.bottom: parent.bottom
                anchors.right: parent.right
            }
            Rectangle {
                width: 2
                height: 15
                color: window.colorCyan
                anchors.bottom: parent.bottom
                anchors.right: parent.right
            }
        }
    }

    Shortcut {
        sequence: "Escape"
        onActivated: Qt.quit()
    }
}
