import QtQuick
import QtQuick.Window

import org.freedesktop.gstreamer.Qt6GLVideoItem 1.0 // Dynamic generated by GStreamer Qt6 QML plugin

Window {
    id: window
    width: 1280
    height: 720
    visible: true
    visibility: Window.FullScreen
    color: "black"

    Item {
        anchors.fill: parent

        GstGLQt6VideoItem {
            id: video
            objectName: "videoItem"
            anchors.centerIn: parent
            width: parent.width
            height: parent.height
        }

        Rectangle {
            anchors.fill: parent
            color: "transparent"
            border.color: "green"
            border.width: 2

            Text {
                text: "GStreamer Rendering"
                color: "green"
                font.pixelSize: 24
                anchors.top: parent.top
                anchors.horizontalCenter: parent.horizontalCenter
                anchors.topMargin: 40
            }
        }
    }

    Shortcut {
        sequence: "Escape"
        onActivated: Qt.quit()
    }
}