set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(QML_MODULE_VERSION_MAJOR 1)
set(QML_MODULE_VERSION_MINOR 0)

if(GEN_TAU_LOG_ENABLED)
  message(STATUS "-> Logging enabled")
  add_compile_definitions(SPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_${GEN_TAU_ACTIVE_LOG_LEVEL})
endif()

set(GT_APP_NAME "gen-tau")
set(GT_QML_MOD_NAME "Gentau.")
set(GT_LIB_PREFIX "gt-")
set(GT_EXPORT_LIB_NS "Gentau::")