// THIS FILE IS AUTOGENERATED FROM CMAKE. DO NOT EDIT!

#pragma once

#define GEN_TAU_VERSION_MAJOR  0
#define GEN_TAU_VERSION_MINOR  1
#define GEN_TAU_VERSION_PATCH  0
#define GEN_TAU_VERSION_STRING "0.1.0"

#define GEN_TAU_DEBUG 1

namespace gentau {
namespace conf {
constexpr bool TDebugMode = (GEN_TAU_DEBUG == 1);
}  
}  // namespace gentau
